export const MAX_NUM_EDITIONS = Number('__MAX_NUM_EDITIONS__') || 20;
export const MAX_NUMBER_OF_SELECTABLE_CONTENT_ITEMS =
  Number('__MAX_NUMBER_OF_SELECTABLE_CONTENT_ITEMS__') || 5;
export const MAX_NUMBER_OF_SELECTABLE_SLOTS =
  Number('__MAX_NUMBER_OF_SELECTABLE_SLOTS__') || 5;
