export const MAX_NUM_EDITIONS = Number('__MAX_NUM_EDITIONS__') || 20;
export const MAX_NUMBER_OF_SELECTABLE_CONTENT_ITEMS =
  Number('__MAX_NUMBER_OF_SELECTABLE_CONTENT_ITEMS__') || 5;
export const MAX_NUMBER_OF_SELECTABLE_SLOTS =
  Number('__MAX_NUMBER_OF_SELECTABLE_SLOTS__') || 5;
export const GOOGLE_ANALYTICS_TIMEOUT =
  Number('__GOOGLE_ANALYTICS_TIMEOUT__') || 30000;
export const GOOGLE_ANALYTICS_TOKEN_EXPIRES_IN = Number(
  '__GOOGLE_ANALYTICS_TOKEN_EXPIRES_IN__'
);
